services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      OPENAI_API_URL:
      OPENAI_API_KEY:
      MODEL_NAME:
      REDIS_URL:
    volumes:
      - ./app.py:/app/app.py
      - ./requirements.txt:/app/requirements.txt
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
    ports:
      - "11434:11434"

volumes:
  ollama: {}
